project:
  type: book

book:
  title: "Quarto CRC Book"
  output-file: "quarto-crc"
  author: "Jane Doe and Max Power"
  date: "11/22/2022"

  chapters:
    - index.qmd
    - Test.ipynb
    - crawling_berita.ipynb
    - Closeness_Centrality.ipynb
    - LDA_Topic_Modelling_PTA.ipynb
    - Ektraksi_Kata_Kunci.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: krantz
    keep-tex: true
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
